name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Security scan job
  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run security scan with CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Basic code quality checks
      run: |
        echo "Running basic code quality checks..."
        
        # Check for debug statements (will be removed in production optimization)
        if grep -r "console\.log" js/ css/ *.html || true; then
          echo "ℹ️  Debug statements found (will be removed in production build)"
        fi
        
        echo "✅ Code quality checks completed"

  # Build and deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js (for any future build steps)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Validate HTML
      run: |
        # Install html5validator
        pip install html5validator
        # Validate HTML files
        html5validator --root . --match "*.html" || echo "HTML validation warnings found"

    - name: Optimize files for production
      run: |
        echo "Preparing files for deployment..."
        
        # Remove debug functions from production JS
        sed -i 's/console\.log.*;//g' js/game.js || true
        
        # Add cache busting to CSS and JS files
        TIMESTAMP=$(date +%s)
        sed -i "s/styles\.css/styles.css?v=$TIMESTAMP/g" index.html
        sed -i "s/game\.js/game.js?v=$TIMESTAMP/g" index.html
        
        echo "✅ Files optimized for production"

    - name: Verify security headers (already in HTML)
      run: |
        # Check if security headers are already present in HTML
        if grep -q "X-Content-Type-Options" index.html; then
          echo "✅ Security headers already present in HTML"
        else
          echo "⚠️  Security headers missing"
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
